server:
  port: 8020
spring:
  application:
    name: consumer #消费者名称为consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #注册中心url
  instance:
    prefer-ip-address: true